### PR TITLE
Implemented Better Layout Using CSS

### PR DESCRIPTION
**Pull request by majordwarf**
- [x] Adding SASS and FontAwesome support.
- [x] Unified typography system.
- [x] Basic card structures for blog post and modules.
- [x] Implement responsive header And the footer.
- [x] Make the layout responsive.

### CODE REVIEW

**Comment by smsunarto** [comment]
It would be great if you can populate `README.md` with the steps to test this code on local.

**Comment by majordwarf** [comment]
I've added a basic readme file having instructions to run the code locally.

**Comment by bpas247** [comment]
What was the original motivation for implementing the styling via SASS?

**Comment by smsunarto** [comment]
You might want to add `gatsby-cli` to `devDependencies` on `package.json`

Read: https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file

**Pull request merged**
