### PR TITLE
[WIP] fetch module data via GitHub GraphQL API

### PR DESCRIPTION
**Pull request by skaldarnar**
<div align="center"><h2>:exclamation: :exclamation: :exclamation:  DO NOT MERGE :exclamation: :exclamation: :exclamation: </h2></div>

This should be split into multiple smaller PRs for simpler review and a better history of the actual changes:

- [x] changes to the `source-terasology-modules` plugin can be isolated in PR (still without it being used)
	- [x]  #182 to fetch cover images and fix some smaller issues
	- [x]  #183 enabled the  `source-terasology-modules` in the CI, needs to provide `GITHUB_ACCESS_TOKEN` in the environment
- [x]  #188 add module pages paginated by first letter (orthogonal to current module pages)
	- [x] remove per-module pages
	- [x] remove old module listings with pagination by index	
- [x] #196 switch navbar link to modules to point to `/modules/a` instead of `modules`
- [x] #203 remove old `modules/` folder with outdated content
- [x] #181 remove `module-generation` scripts and utilities

### CODE REVIEW

**Comment by skaldarnar** [comment]
Storing `Module.jsx` for later reference:

```jsx
import React from "react";
import { graphql } from "gatsby";
import { GatsbyImage, getImage } from "gatsby-plugin-image";
import { Badge } from "reactstrap";
import Layout from "../layout";
import SocialLinks from "../components/SocialLinks/SocialLinks";
import SEO from "../components/SEO/SEO";
import config from "../../data/SiteConfig";
import { FaGithub, FaLink } from "react-icons/fa";

function Module({ data }) {
  console.log(JSON.stringify(data, null, 2));
  const { terasologyModule, file } = data;
  const { name, description, url, homepageUrl, moduleTxt } = terasologyModule;

  const {version, tags} = moduleTxt;

  return (
    <Layout>
      <div>
        <div>
          <GatsbyImage className="post-cover" image={getImage(data.file)} />

          <h1 className="text-center">{name}</h1>
          <div className="title-underline" />
          <div>
            {tags.map((tag) => (
              <Badge>{tag}</Badge>
            ))}
          </div>
          <div>
            {version}
          </div>
          <div>
            <p>{description}</p>
            <p>
              <a href={url} target="_blank">
                <FaGithub /> View on GitHub.
              </a>
            </p>
            {homepageUrl ? (
              <p>
                <a href={homepageUrl} target="_blank">
                  <FaLink /> Website
                </a>
              </p>
            ) : (
              ""
            )}
          </div>
          <div className="post-meta">
            <SocialLinks
              title={name}
              excerpt={description}
              path={`/modules/${name}`}
            />
          </div>
        </div>
      </div>
    </Layout>
  );
}

export default Module;

export const query = graphql`
  query Module($name: String) {
    terasologyModule(name: { eq: $name }) {
      name
      description
      url
      homepageUrl
      moduleTxt {
        version
        tags
      }
    }

    file(relativePath: { eq: "logos/defaultCardcover.jpg" }) {
      childImageSharp {
        gatsbyImageData
      }
    }
  }
`;

export function Head({ data, pageContext }) {
  return (
    <SEO
      pathname={pageContext.slug}
      title={`${pageContext.name} | ${config.siteTitle}`}
    />
  );
}
```

**Comment by skaldarnar** [comment]
image

**Comment by jdrueckert** [comment]
Repository secret created, it's called `MODULE_FETCH_GITHUB_TOKEN`

**Comment by jdrueckert** [comment]
This PR was spread out into multiple smaller ones (see PR description).

**Pull request closed without merging**
